
   
name: Docker Image CI

on:
  push:
    branches: [ master, dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leonardof45/aurora-pets-service:${{ steps.extract_branch.outputs.branch }}
      
    - name: Docker Push
      run: docker push leonardof45/aurora-pets-service:${{ steps.extract_branch.outputs.branch }}
